version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: rhymer-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  python:
    build:
      context: ./src
    container_name: rhymer-python
    depends_on:
      - mongodb
    volumes:
      - ./src:/usr/src/app

volumes:
  mongo_data:
