version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: my-mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  python-app:
    build:
      context: ./src
    container_name: my-python-app-container
    depends_on:
      - mongodb

volumes:
  mongo_data:
